version: 2.1

executors:
  terraform:
    docker:
    - image: hashicorp/terraform:light

jobs:
  terraform-format-check:
    executor: terraform
    steps:
    - checkout
    - run:
        name: Check terraform formatting
        command: |
          terraform fmt -recursive -check
  terraform-validation-check:
    executor: terraform
    steps:
    - checkout
    - run:
        name: Configure a stub provider for testing
        command: echo "provider \"aws\" { region = \"us-east-1\" } " > tmp_provider.tf
    - run: terraform init -backend=false -input=false
    - run: terraform validate

workflows:
  version: 2
  branch_workflow:
    jobs:
    - terraform-format-check
    - terraform-validation-check
